### ISSUE TITLE
可否给点详细说明

### ISSUE THREAD

**Issue by woytu** [caeret/gitlab-ce-zh#1]
比如安装配置，还有能否升级等？

**Comment by caeret** [comment]
@woytu 
你好，可以使用 docker-compose 启动服务，配置已经更新在 README.md 了。
需要注意端口冲突问题。

**Comment by woytu** [comment]
> @woytu
> 你好，可以使用 docker-compose 启动服务，配置已经更新在 README.md 了。
> 需要注意端口冲突问题。

非常感谢
