### ISSUE TITLE
请问怎么从 11.10.4 升级到 12.1.0?

### ISSUE THREAD

**Issue by IT513** [caeret/gitlab-ce-zh#2]
docker 环境 直接 指向11.10.4 启动不了，重新使用 11.10.4就可以
有什么办法直接升级吗？
- ${PWD}/config:/etc/gitlab
- ${PWD}/data:/var/opt/gitlab
- ${PWD}/logs:/var/log/gitlab

**Comment by caeret** [comment]
> docker 环境 直接 指向11.10.4 启动不了

方便告知做了什么操作后启动不了吗？
